name: "Deploy"
description: 'Deploy App'
inputs:
  function:  # id of input
    description: 'Name of function'
    required: true
  serviceKey:
    description: 'Service Account Key'
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.serviceKey }}'

    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
        path: out

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'deploy'
      shell: bash
      run: "gcloud functions deploy ${{ inputs.function }} --region=europe-west6 --runtime=nodejs20 --source=out --entry-point=telegraf --trigger-http --gen2 --allow-unauthenticated"