name: memobot
services:
  memobot:
    image: "mcr.microsoft.com/azure-functions/node:4"
    ports:
      - 5800:80
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      PUBLIC_URL: "${PUBLIC_URL}"
    volumes:
      - ../dist/index.js:/home/site/wwwroot/dist/main.js
      - ../node_modules:/home/site/wwwroot/node_modules
      - ../package.json:/home/site/wwwroot/package.json
      - ../host.json:/home/site/wwwroot/host.json
      - ../local.settings.json:/home/site/wwwroot/settings.json
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd12"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"