UPDATE "Word" SET "description" = 'to suggest an idea or opinion' WHERE "word" = 'ADVANCE';
UPDATE "Word" SET "description" = 'to say strongly that something is true' WHERE "word" = 'ASSERT';
UPDATE "Word" SET "description" = 'a guess made without full proof' WHERE "word" = 'CONJECTURE';
UPDATE "Word" SET "description" = 'an idea you believe before you have proof' WHERE "word" = '(PRE)SUPPOSITION';
UPDATE "Word" SET "description" = 'to guess something without strong proof' WHERE "word" = 'SURMISE';
UPDATE "Word" SET "description" = 'to make an idea or opinion stronger' WHERE "word" = 'BOLSTER';
UPDATE "Word" SET "description" = 'to give extra support to an idea' WHERE "word" = 'BUTTRESS';
UPDATE "Word" SET "description" = 'to show proof that something is true' WHERE "word" = 'SUBSTANTIATE';
UPDATE "Word" SET "description" = 'to agree with or confirm what someone said' WHERE "word" = 'CORROBORATE';
UPDATE "Word" SET "description" = 'to show that something is correct or true' WHERE "word" = 'VALIDATE';
UPDATE "Word" SET "description" = 'to admit that the other side is right' WHERE "word" = 'CONCEDE';
UPDATE "Word" SET "description" = 'to accept that something is true' WHERE "word" = 'ACKNOWLEDGE';
UPDATE "Word" SET "description" = 'to argue against an idea you think is wrong' WHERE "word" = 'REBUT';
UPDATE "Word" SET "description" = 'to prove that something is not true' WHERE "word" = 'REFUTE';
UPDATE "Word" SET "description" = 'to try hard to solve or understand a problem' WHERE "word" = 'GRAPPLE WITH';
UPDATE "Word" SET "description" = 'to think about something for a long time' WHERE "word" = 'RUMINATE ABOUT';
UPDATE "Word" SET "description" = 'to guess based on facts you have' WHERE "word" = 'INFER';
UPDATE "Word" SET "description" = 'a person who supports an idea or plan' WHERE "word" = 'PROPONENT';
UPDATE "Word" SET "description" = 'a person who says bad things about an idea' WHERE "word" = 'DETRACTOR';
UPDATE "Word" SET "description" = 'a person who has doubts about an idea' WHERE "word" = 'SKEPTIC';
UPDATE "Word" SET "description" = 'sudden and not expected' WHERE "word" = 'ABRUPT';
UPDATE "Word" SET "description" = 'very firm; not willing to change your mind' WHERE "word" = 'ADAMANT';
UPDATE "Word" SET "description" = 'more than enough; in large amounts' WHERE "word" = 'ABUNDANT';
UPDATE "Word" SET "description" = 'to make something easier to see or notice' WHERE "word" = 'ACCENTUATE';
UPDATE "Word" SET "description" = 'strong public praise' WHERE "word" = 'ACCLAIM';
UPDATE "Word" SET "description" = 'a change to fit a new situation' WHERE "word" = 'ADAPTATION';
UPDATE "Word" SET "description" = 'helpful; giving a good result' WHERE "word" = 'ADVANTAGEOUS';
UPDATE "Word" SET "description" = 'about beauty or how something looks' WHERE "word" = 'AESTHETIC';
UPDATE "Word" SET "description" = 'making you feel strong emotions' WHERE "word" = 'AFFECTING';
UPDATE "Word" SET "description" = 'a strong feeling of liking' WHERE "word" = 'AFFINITY';
UPDATE "Word" SET "description" = 'not clear; can be understood in more than one way' WHERE "word" = 'AMBIGUOUS';
UPDATE "Word" SET "description" = 'having both good and bad feelings about something' WHERE "word" = 'AMBIVALENCE';
UPDATE "Word" SET "description" = 'to make something better' WHERE "word" = 'AMELIORATE';
UPDATE "Word" SET "description" = 'with no clear shape' WHERE "word" = 'AMORPHOUS';
UPDATE "Word" SET "description" = 'a comparison that helps explain something' WHERE "word" = 'ANALOGY';
UPDATE "Word" SET "description" = 'strong dislike or hate' WHERE "word" = 'ANIMOSITY';
UPDATE "Word" SET "description" = 'to add notes that explain something' WHERE "word" = 'ANNOTATE';
UPDATE "Word" SET "description" = 'something different from what is normal' WHERE "word" = 'ANOMALY';
UPDATE "Word" SET "description" = 'completely opposite' WHERE "word" = 'ANTITHETICAL';
UPDATE "Word" SET "description" = 'to calm someone by giving them what they want' WHERE "word" = 'APPEASE';
UPDATE "Word" SET "description" = 'to judge how good or valuable something is' WHERE "word" = 'APPRAISE';
UPDATE "Word" SET "description" = 'close to but not exactly correct' WHERE "word" = 'APPROXIMATE';
UPDATE "Word" SET "description" = 'to make bigger or add more' WHERE "word" = 'AUGMENT';
UPDATE "Word" SET "description" = 'very simple, with no decoration' WHERE "word" = 'AUSTERE';
UPDATE "Word" SET "description" = 'to make something happen faster' WHERE "word" = 'CATALYZE';
UPDATE "Word" SET "description" = 'very bad; causing great damage' WHERE "word" = 'CATASTROPHIC';
UPDATE "Word" SET "description" = 'to stop' WHERE "word" = 'CEASE';
UPDATE "Word" SET "description" = 'to find a way to avoid a problem or rule' WHERE "word" = 'CIRCUMVENT';
UPDATE "Word" SET "description" = 'to mention a source as proof' WHERE "word" = 'CITE';
UPDATE "Word" SET "description" = 'to come together as one' WHERE "word" = 'COALESCE';
UPDATE "Word" SET "description" = 'rough quality; not smooth' WHERE "word" = 'COARSENESS';
UPDATE "Word" SET "description" = 'working together with others' WHERE "word" = 'COLLABORATION';
UPDATE "Word" SET "description" = 'very common; normal' WHERE "word" = 'COMMONPLACE';
UPDATE "Word" SET "description" = 'to be made up of; to include' WHERE "word" = 'COMPRISE';
UPDATE "Word" SET "description" = 'to keep something inside a small area' WHERE "word" = 'CONFINE';
UPDATE "Word" SET "description" = 'to confuse someone completely' WHERE "word" = 'CONFOUND';
UPDATE "Word" SET "description" = 'agreement among most people' WHERE "word" = 'CONSENSUS';
UPDATE "Word" SET "description" = 'easy to see or notice' WHERE "word" = 'CONSPICUOUS';
UPDATE "Word" SET "description" = 'eating, drinking, or using something' WHERE "word" = 'CONSUMPTION';
UPDATE "Word" SET "description" = 'depending on something else' WHERE "word" = 'CONTINGENT';
UPDATE "Word" SET "description" = 'to plan or invent something' WHERE "word" = 'CONTRIVE';
UPDATE "Word" SET "description" = 'in large amounts' WHERE "word" = 'COPIOUS';
UPDATE "Word" SET "description" = 'easy to believe' WHERE "word" = 'CREDIBLE';
UPDATE "Word" SET "description" = 'ready to believe anything; easy to trick' WHERE "word" = 'CREDULOUS';
UPDATE "Word" SET "description" = 'a total failure' WHERE "word" = 'DEBACLE';
UPDATE "Word" SET "description" = 'to use up; to reduce a lot' WHERE "word" = 'DEPLETE';
UPDATE "Word" SET "description" = 'feeling very sad and without hope' WHERE "word" = 'DESPONDENT';
UPDATE "Word" SET "description" = 'moving away from what is normal' WHERE "word" = 'DEVIATION';
UPDATE "Word" SET "description" = 'skillful with your hands' WHERE "word" = 'DEXTEROUS';
UPDATE "Word" SET "description" = 'able to be seen or noticed' WHERE "word" = 'DISCERNIBLE';
UPDATE "Word" SET "description" = 'disagreement between people' WHERE "word" = 'DISCORD';
UPDATE "Word" SET "description" = 'very different from each other' WHERE "word" = 'DISPARATE';
UPDATE "Word" SET "description" = 'to spread in different directions' WHERE "word" = 'DISPERSE';
UPDATE "Word" SET "description" = 'your usual mood or character' WHERE "word" = 'DISPOSITION';
UPDATE "Word" SET "description" = 'to go in different directions' WHERE "word" = 'DIVERGE';
UPDATE "Word" SET "description" = 'making a wild animal or plant useful for people' WHERE "word" = 'DOMESTICATION';
UPDATE "Word" SET "description" = 'very strict and harsh' WHERE "word" = 'DRACONIAN';
UPDATE "Word" SET "description" = 'strange or unusual in behavior' WHERE "word" = 'ECCENTRIC';
UPDATE "Word" SET "description" = 'to be much better than something else' WHERE "word" = 'ECLIPSE';
UPDATE "Word" SET "description" = 'to get a reaction or answer from someone' WHERE "word" = 'ELICIT';
UPDATE "Word" SET "description" = 'hard to find or catch' WHERE "word" = 'ELUSIVE';
UPDATE "Word" SET "description" = 'to cause something to happen' WHERE "word" = 'ENGENDER';
UPDATE "Word" SET "description" = 'to cover or surround completely' WHERE "word" = 'ENGULF';
UPDATE "Word" SET "description" = 'to make better or stronger' WHERE "word" = 'ENHANCE';
UPDATE "Word" SET "description" = 'lasting only a short time' WHERE "word" = 'EPHEMERAL';
UPDATE "Word" SET "description" = 'fair and equal for everyone' WHERE "word" = 'EQUITABLE';
UPDATE "Word" SET "description" = 'not regular; changing without reason' WHERE "word" = 'ERRATIC';
UPDATE "Word" SET "description" = 'to escape from or avoid something' WHERE "word" = 'EVADE';
UPDATE "Word" SET "description" = 'to show a feeling clearly' WHERE "word" = 'EVINCE';
UPDATE "Word" SET "description" = 'to make a problem worse' WHERE "word" = 'EXACERBATE';
UPDATE "Word" SET "description" = 'digging in the ground to find old things' WHERE "word" = 'EXCAVATION';
UPDATE "Word" SET "description" = 'much too high (a price)' WHERE "word" = 'EXORBITANT';
UPDATE "Word" SET "description" = 'said in a clear and direct way' WHERE "word" = 'EXPLICIT';
UPDATE "Word" SET "description" = 'to use someone or something for your own benefit' WHERE "word" = 'EXPLOIT';
UPDATE "Word" SET "description" = 'the state of being in contact with something' WHERE "word" = 'EXPOSURE';
UPDATE "Word" SET "description" = 'to make up a lie' WHERE "word" = 'FABRICATE';
UPDATE "Word" SET "description" = 'an outside look that hides the truth' WHERE "word" = 'FACADE';
UPDATE "Word" SET "description" = 'to help something good grow' WHERE "word" = 'FOSTER';
UPDATE "Word" SET "description" = 'giving good results / giving no results' WHERE "word" = 'FRUITFUL/FRUITLESS';
UPDATE "Word" SET "description" = 'to make people excited and ready to act' WHERE "word" = 'GALVANIZE';
UPDATE "Word" SET "description" = 'without a plan; messy' WHERE "word" = 'HAPHAZARD';
UPDATE "Word" SET "description" = 'made of many different parts' WHERE "word" = 'HETEROGENEOUS';
UPDATE "Word" SET "description" = 'to make it harder to do something' WHERE "word" = 'HINDER';
UPDATE "Word" SET "description" = 'to think something is better than it really is' WHERE "word" = 'IDEALIZE';
UPDATE "Word" SET "description" = 'special only to one person' WHERE "word" = 'IDIOSYNCRATIC';
UPDATE "Word" SET "description" = 'not real; only seems to be true' WHERE "word" = 'ILLUSORY';
UPDATE "Word" SET "description" = 'going to happen very soon' WHERE "word" = 'IMMINENT';
UPDATE "Word" SET "description" = 'to slow down or stop something' WHERE "word" = 'IMPEDE';
UPDATE "Word" SET "description" = 'perfect; with no mistakes' WHERE "word" = 'IMPECCABLE';
UPDATE "Word" SET "description" = 'impossible to enter or pass through' WHERE "word" = 'IMPENETRABLE';
UPDATE "Word" SET "description" = 'very important; must be done' WHERE "word" = 'IMPERATIVE';
UPDATE "Word" SET "description" = 'too small to see or notice' WHERE "word" = 'IMPERCEPTIBLE';
UPDATE "Word" SET "description" = 'big and impressive to look at' WHERE "word" = 'IMPOSING';
UPDATE "Word" SET "description" = 'very poor; with no money' WHERE "word" = 'IMPOVERISHED';
UPDATE "Word" SET "description" = 'not fitting with what is around it' WHERE "word" = 'INCONGRUOUS';
UPDATE "Word" SET "description" = 'impossible to read or understand' WHERE "word" = 'INDECIPHERABLE';
UPDATE "Word" SET "description" = 'impossible to forget or remove' WHERE "word" = 'INDELIBLE';
UPDATE "Word" SET "description" = 'not interested; not caring' WHERE "word" = 'INDIFFERENT';
UPDATE "Word" SET "description" = 'native; from a place originally' WHERE "word" = 'INDIGENOUS';
UPDATE "Word" SET "description" = 'to teach people to believe ideas without question' WHERE "word" = 'INDOCTRINATE';
UPDATE "Word" SET "description" = 'to make someone do something' WHERE "word" = 'INDUCE';
UPDATE "Word" SET "description" = 'too kind; not strict enough' WHERE "word" = 'INDULGENT';
UPDATE "Word" SET "description" = 'impossible to avoid' WHERE "word" = 'INELUCTABLE';
UPDATE "Word" SET "description" = 'never wrong; never makes mistakes' WHERE "word" = 'INFALLIBLE';
UPDATE "Word" SET "description" = 'very, very small' WHERE "word" = 'INFINITESIMAL';
UPDATE "Word" SET "description" = 'very clever and creative' WHERE "word" = 'INGENIOUS';
UPDATE "Word" SET "description" = 'not dangerous; safe' WHERE "word" = 'INNOCUOUS';
UPDATE "Word" SET "description" = 'using new ideas; modern' WHERE "word" = 'INNOVATIVE';
UPDATE "Word" SET "description" = 'a clear and deep understanding' WHERE "word" = 'INSIGHT';
UPDATE "Word" SET "description" = 'a large art display in a public place' WHERE "word" = 'INSTALLATION';
UPDATE "Word" SET "description" = 'too difficult to overcome' WHERE "word" = 'INSUPERABLE';
UPDATE "Word" SET "description" = 'too big to deal with or beat' WHERE "word" = 'INSURMOUNTABLE';
UPDATE "Word" SET "description" = 'in the middle between two levels' WHERE "word" = 'INTERMEDIATE';
UPDATE "Word" SET "description" = 'very detailed and complex' WHERE "word" = 'INTRICATE';
UPDATE "Word" SET "description" = 'very interesting; making you want to know more' WHERE "word" = 'INTRIGUING';
UPDATE "Word" SET "description" = 'a feeling that tells you something without thinking' WHERE "word" = 'INTUITION';
UPDATE "Word" SET "description" = 'spreading in a way that causes harm' WHERE "word" = 'INVASIVE';
UPDATE "Word" SET "description" = 'very angry' WHERE "word" = 'IRATE';
UPDATE "Word" SET "description" = 'with no mistakes; perfect' WHERE "word" = 'IRREPROACHABLE';
UPDATE "Word" SET "description" = 'cannot be changed or stopped' WHERE "word" = 'IRREVOCABLE';
UPDATE "Word" SET "description" = 'placing two things side by side to compare them' WHERE "word" = 'JUXTAPOSITION';
UPDATE "Word" SET "description" = 'using very few words' WHERE "word" = 'LACONIC';
UPDATE "Word" SET "description" = 'present but hidden; not active yet' WHERE "word" = 'LATENT';
UPDATE "Word" SET "description" = 'something important left from the past' WHERE "word" = 'LEGACY';
UPDATE "Word" SET "description" = 'your family line through history' WHERE "word" = 'LINEAGE';
UPDATE "Word" SET "description" = 'earning a lot of money' WHERE "word" = 'LUCRATIVE';
UPDATE "Word" SET "description" = 'a sign that shows something is real or present' WHERE "word" = 'MANIFESTATION';
UPDATE "Word" SET "description" = 'with quickly changing moods' WHERE "word" = 'MERCURIAL';
UPDATE "Word" SET "description" = 'very careful about small details' WHERE "word" = 'METICULOUS';
UPDATE "Word" SET "description" = 'moving from one place to another' WHERE "word" = 'MIGRATION';
UPDATE "Word" SET "description" = 'to understand wrongly' WHERE "word" = 'MISCONSTRUE';
UPDATE "Word" SET "description" = 'to make a bad thing less serious' WHERE "word" = 'MITIGATE';
UPDATE "Word" SET "description" = 'to get people ready to act' WHERE "word" = 'MOBILIZE';
UPDATE "Word" SET "description" = 'very important (a decision or event)' WHERE "word" = 'MOMENTOUS';
UPDATE "Word" SET "description" = 'to earn money from something' WHERE "word" = 'MONETIZE';
UPDATE "Word" SET "description" = 'almost dead or no longer used' WHERE "word" = 'MORIBUND';
UPDATE "Word" SET "description" = 'having many different sides or parts' WHERE "word" = 'MULTIFACETED';
UPDATE "Word" SET "description" = 'boring and ordinary' WHERE "word" = 'MUNDANE';
UPDATE "Word" SET "description" = 'a very large number' WHERE "word" = 'MYRIAD';
UPDATE "Word" SET "description" = 'not clear; without a clear shape' WHERE "word" = 'NEBULOUS';
UPDATE "Word" SET "description" = 'very bad and evil' WHERE "word" = 'NEFARIOUS';
UPDATE "Word" SET "description" = 'a small difference in meaning' WHERE "word" = 'NUANCE';
UPDATE "Word" SET "description" = 'to take care of and help grow' WHERE "word" = 'NURTURE';
UPDATE "Word" SET "description" = 'not well known; hard to understand' WHERE "word" = 'OBSCURE';
UPDATE "Word" SET "description" = 'said without thinking first' WHERE "word" = 'OFFHAND';
UPDATE "Word" SET "description" = 'making you feel something bad will happen' WHERE "word" = 'OMINOUS';
UPDATE "Word" SET "description" = 'the direction of your interests or feelings' WHERE "word" = 'ORIENTATION';
UPDATE "Word" SET "description" = 'following common beliefs or rules' WHERE "word" = 'ORTHODOX';
UPDATE "Word" SET "description" = 'too much work or pressure' WHERE "word" = 'OVERLOAD';
UPDATE "Word" SET "description" = 'to be more important and hide the value of others' WHERE "word" = 'OVERSHADOW';
UPDATE "Word" SET "description" = 'old and not used anymore' WHERE "word" = 'OUTMODED';
UPDATE "Word" SET "description" = 'much bigger than normal' WHERE "word" = 'OUTSIZED';
UPDATE "Word" SET "description" = 'so strong you can almost feel it' WHERE "word" = 'PALPABLE';
UPDATE "Word" SET "description" = 'a very small amount; not enough' WHERE "word" = 'PAUCITY';
UPDATE "Word" SET "description" = 'less important; on the side' WHERE "word" = 'PERIPHERAL';
UPDATE "Word" SET "description" = 'found everywhere; very common' WHERE "word" = 'PERVASIVE';
UPDATE "Word" SET "description" = 'completely opposite' WHERE "word" = 'POLAR';
UPDATE "Word" SET "description" = 'practical; based on what works' WHERE "word" = 'PRAGMATIC';
UPDATE "Word" SET "description" = 'to make something happen suddenly' WHERE "word" = 'PRECIPITATE';
UPDATE "Word" SET "description" = 'to stop something from happening' WHERE "word" = 'PRECLUDE';
UPDATE "Word" SET "description" = 'something that came before another thing' WHERE "word" = 'PRECURSOR';
UPDATE "Word" SET "description" = 'hunting or hurting weaker people or animals' WHERE "word" = 'PREDATORY';
UPDATE "Word" SET "description" = 'knowing what will happen in the future' WHERE "word" = 'PRESCIENT';
UPDATE "Word" SET "description" = 'to set a rule that must be followed' WHERE "word" = 'PRESCRIBE';
UPDATE "Word" SET "description" = 'trying to seem more important than you are' WHERE "word" = 'PRETENTIOUS';
UPDATE "Word" SET "description" = 'a false reason given to hide the real one' WHERE "word" = 'PRETEXT';
UPDATE "Word" SET "description" = 'to win even when things are difficult' WHERE "word" = 'PREVAIL';
UPDATE "Word" SET "description" = 'to put the most important things first' WHERE "word" = 'PRIORITIZE';
UPDATE "Word" SET "description" = 'very large and impressive' WHERE "word" = 'PRODIGIOUS';
UPDATE "Word" SET "description" = 'very deep and meaningful' WHERE "word" = 'PROFOUND';
UPDATE "Word" SET "description" = 'a very large amount' WHERE "word" = 'PROFUSION';
UPDATE "Word" SET "description" = 'too high or hard, so it stops something' WHERE "word" = 'PROHIBITIVE';
UPDATE "Word" SET "description" = 'producing a lot of work' WHERE "word" = 'PROLIFIC';
UPDATE "Word" SET "description" = 'causing strong feelings, often anger' WHERE "word" = 'PROVOCATIVE';
UPDATE "Word" SET "description" = 'to say you no longer believe what you said' WHERE "word" = 'RECANT';
UPDATE "Word" SET "description" = 'to do the same thing back to someone' WHERE "word" = 'RECIPROCATE';
UPDATE "Word" SET "description" = 'to make peace between people who were fighting' WHERE "word" = 'RECONCILE';
UPDATE "Word" SET "description" = '(n.) an official list; (v.) to add to a list or notice' WHERE "word" = 'REGISTER';
UPDATE "Word" SET "description" = 'connected to the topic / not connected to the topic' WHERE "word" = 'RELEVANT/IRRELEVANT';
UPDATE "Word" SET "description" = 'to give up officially; to refuse' WHERE "word" = 'RENOUNCE';
UPDATE "Word" SET "description" = 'to fill again with what was used' WHERE "word" = 'REPLENISH';
UPDATE "Word" SET "description" = 'to make an exact copy' WHERE "word" = 'REPLICATE';
UPDATE "Word" SET "description" = 'able to recover quickly from problems' WHERE "word" = 'RESILIENT';
UPDATE "Word" SET "description" = 'becoming popular or active again' WHERE "word" = 'RESURGENCE';
UPDATE "Word" SET "description" = 'looking back at the past' WHERE "word" = 'RETROSPECT';
UPDATE "Word" SET "description" = 'a surprising fact that becomes known' WHERE "word" = 'REVELATION';
UPDATE "Word" SET "description" = 'very basic; only the simplest parts' WHERE "word" = 'RUDIMENTARY';
UPDATE "Word" SET "description" = 'to damage something on purpose' WHERE "word" = 'SABOTAGE';
UPDATE "Word" SET "description" = 'to fully fill or satisfy' WHERE "word" = 'SATIATE';
UPDATE "Word" SET "description" = 'a clever plan, often dishonest' WHERE "word" = 'SCHEME';
UPDATE "Word" SET "description" = 'very careful and honest' WHERE "word" = 'SCRUPULOUS';
UPDATE "Word" SET "description" = 'to look at very carefully' WHERE "word" = 'SCRUTINIZE(n. SCRUTINY)';
UPDATE "Word" SET "description" = 'to guess about something without proof' WHERE "word" = 'SPECULATE';
UPDATE "Word" SET "description" = 'false; not real' WHERE "word" = 'SPURIOUS';
UPDATE "Word" SET "description" = 'to state a clear condition in an agreement' WHERE "word" = 'STIPULATE';
UPDATE "Word" SET "description" = 'needing a lot of physical effort' WHERE "word" = 'STRENUOUS';
UPDATE "Word" SET "description" = 'based on personal feelings, not facts' WHERE "word" = 'SUBJECTIVE';
UPDATE "Word" SET "description" = 'large in size or importance' WHERE "word" = 'SUBSTANTIAL';
UPDATE "Word" SET "description" = 'only on the surface; not deep' WHERE "word" = 'SUPERFICIAL';
UPDATE "Word" SET "description" = 'more than needed; not necessary' WHERE "word" = 'SUPERFLUOUS';
UPDATE "Word" SET "description" = 'to take the place of something' WHERE "word" = 'SUPPLANT';
UPDATE "Word" SET "description" = '(n.) something extra added; (v.) to add more' WHERE "word" = 'SUPPLEMENT';
UPDATE "Word" SET "description" = 'to be better or greater than' WHERE "word" = 'SURPASS';
UPDATE "Word" SET "description" = 'to change someone''s opinion' WHERE "word" = 'SWAY';
UPDATE "Word" SET "description" = 'to make things happen at the same time' WHERE "word" = 'SYNCHRONIZE';
UPDATE "Word" SET "description" = 'a short summary' WHERE "word" = 'SYNOPSIS';
UPDATE "Word" SET "description" = '(n.) a count or total; (v.) to count' WHERE "word" = 'TALLY';
UPDATE "Word" SET "description" = 'to stop someone''s plan from working' WHERE "word" = 'THWART';
UPDATE "Word" SET "description" = 'to go beyond normal limits' WHERE "word" = 'TRANSCEND';
UPDATE "Word" SET "description" = 'long, boring, and tiring' WHERE "word" = 'TEDIOUS';
UPDATE "Word" SET "description" = 'weak; not strong' WHERE "word" = 'TENUOUS';
UPDATE "Word" SET "description" = 'not important; small' WHERE "word" = 'TRIVIAL';
UPDATE "Word" SET "description" = 'found everywhere' WHERE "word" = 'UBIQUITOUS';
UPDATE "Word" SET "description" = 'impossible to reach or get' WHERE "word" = 'UNATTAINABLE';
UPDATE "Word" SET "description" = 'strange in a way that is hard to explain' WHERE "word" = 'UNCANNY';
UPDATE "Word" SET "description" = 'impossible to put into a group' WHERE "word" = 'UNCLASSIFIABLE';
UPDATE "Word" SET "description" = 'not following the usual way' WHERE "word" = 'UNCONVENTIONAL';
UPDATE "Word" SET "description" = 'to make something weaker little by little' WHERE "word" = 'UNDERMINE';
UPDATE "Word" SET "description" = 'to show that something is important' WHERE "word" = 'UNDERSCORE';
UPDATE "Word" SET "description" = 'very clear; with no doubt' WHERE "word" = 'UNEQUIVOCAL';
UPDATE "Word" SET "description" = 'quiet; not getting attention' WHERE "word" = 'UNOBTRUSIVE';
UPDATE "Word" SET "description" = 'impossible to fix or solve' WHERE "word" = 'UNRESOLVABLE';
UPDATE "Word" SET "description" = 'impossible to defend or keep' WHERE "word" = 'UNTENABLE';
UPDATE "Word" SET "description" = 'to keep changing your mind between choices' WHERE "word" = 'VACILLATE';
UPDATE "Word" SET "description" = 'to prove that something is true' WHERE "word" = 'VALIDATE';
UPDATE "Word" SET "description" = 'looking or sounding like the truth' WHERE "word" = 'VERISIMILITUDE';
UPDATE "Word" SET "description" = 'to prove that someone was right' WHERE "word" = 'VINDICATE';
UPDATE "Word" SET "description" = 'to give up a right by your own choice' WHERE "word" = 'WAIVE';
UPDATE "Word" SET "description" = 'to keep changing your mind' WHERE "word" = 'WAVER';
UPDATE "Word" SET "description" = 'an important moment of change' WHERE "word" = 'WATERSHED';
