name: "Deploy"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.GCLOUD_WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: 'github@spixmemo.iam.gserviceaccount.com' # e.g. - my-service-account@my-project.iam.gserviceaccount.com


      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: out

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'deploy api'
        env:
          function: ${{ github.ref == 'refs/heads/main' && 'telegram' || 'telegram-stage' }}
          token: ${{ github.ref == 'refs/heads/main' && secrets.BOT_TOKEN || secrets.BOT_TOKEN_STAGE }}
          env: ${{ github.ref == 'refs/heads/main' && 'production' || 'stage' }}
          region: 'europe-west6'
          project: 'spixmemo'
        run: |
          gcloud functions deploy ${{ env.function }} \
            --region=${{ env.region }} --runtime=nodejs22 --source=out \
            --entry-point=telegram --trigger-http --gen2 --allow-unauthenticated \
            --timeout=1800 \
            --set-env-vars=BOT_TOKEN=${{ env.token}} \
            --set-env-vars=ENVIRONMENT=${{ env.env }} \
            --set-env-vars=PLAN_SHEET_ID=${{ secrets.PLAN_SHEET_ID }} \
            --set-env-vars=DATABASE_USER=postgres \
            --set-env-vars=DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --set-env-vars=DATABASE_HOST=10.101.32.3 \
            --set-env-vars=DATABASE_PORT=5432 \
            --set-env-vars=DATABASE_DB=memobot-dev \
            --set-env-vars=DATABASE_URL=postgresql://postgres:${{ secrets.DB_PASSWORD }}@10.101.32.3:5432/memobot-dev \
            --set-env-vars=PUBLIC_URL=https://${{ env.function }}-5580233934.europe-west6.run.app \
            --run-service-account=app-runner@${{ env.project }}.iam.gserviceaccount.com \
            --build-service-account=projects/${{ env.project}}/serviceAccounts/github@${{ env.project }}.iam.gserviceaccount.com

