name: "Deploy"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.GCLOUD_WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: 'github@steel-topic-444112-i8.iam.gserviceaccount.com' # e.g. - my-service-account@my-project.iam.gserviceaccount.com


      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: out

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'deploy'
        env:
          function: ${{ github.ref == 'refs/heads/main' && 'telegraf' || 'telegraf-stage' }}
          token: ${{ github.ref == 'refs/heads/main' && secrets.BOT_TOKEN || secrets.BOT_TOKEN_STAGE }}
          env: ${{ github.ref == 'refs/heads/main' && 'production' || 'stage' }}
          region: 'europe-west6'
          project: 'steel-topic-444112-i8'
        run: |
          gcloud functions deploy ${{ env.function }} \
            --region=${{ env.region }} --runtime=nodejs20 --source=out \
            --entry-point=telegraf --trigger-http --gen2 --allow-unauthenticated \
            --set-env-vars=BOT_TOKEN=${{ env.token}} \
            --set-env-vars=ENVIRONMENT=${{ env.env }} \
            --set-env-vars=PUBLIC_URL=https://${{ env.function }}-602612727393.europe-west6.run.app \
            --run-service-account=app-runner@${{ env.project }}.iam.gserviceaccount.com \
            --build-service-account=projects/${{ env.project}}/serviceAccounts/github@${{ env.project }}.iam.gserviceaccount.com