# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - spixmemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build
        run: |
          yarn
          yarn run compile
          yarn run bundle
      - name: output
        run: |
          mkdir ./out/dist -p
          cp ./dist/index.cjs ./out/dist/index.cjs
          cp ./package.json ./out/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./out/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          
      - name: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v2'
        timeout-minutes: 10
        with:
          name: 'telegraf'
          runtime: 'nodejs20'
          region: 'europe-west1'
          entry_point: 'telegraf'
          memory_mb: 128,
          min_instances: 1
          max_instances: 2